name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Git configuration 
    - name: Set up Git config
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
    
    # Set up Node.js 
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your node version
    
    # Install dependencies 
    - name: Install dependencies
      run: |
        npm install

    # Build the project 
    - name: Build the project
      run: |
        npm run build

    # Deploy 
    - name: Deploy to GitHub Pages (or any deploy action)
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}